### ISSUE TITLE
Problems in the React Forms section of the course

### ISSUE THREAD

**Issue by Joeriksson** [testdrivenio/taxi-react-app#1]
In the React Forms section of the course there is a cypress test to test 'Can sign up'. It is using the cypress-file-upload. In the course it says the code should be:

```
cy.fixture('images/photo.jpg').then(photo => {
            cy.get('input#photo').upload({
                fileContent: photo,
                fileName: 'photo.jpg',
                mimeType: 'application/json'
            });
```
I couldn't get that to work. There was an error "TypeError: cy.get(...).upload is not a function". Looking at the documentation at https://www.npmjs.com/package/cypress-file-upload. There is currently no upload function, but an attachFile function. 

So to get it to work I had to change the code to:

```
cy.fixture('images/photo.png').then(photo => {
            cy.get('input#photo').attachFile('images/photo.png')
        });
```

**Comment by mjhea0** [comment]
Fixed!
